console.log("Первая задача");
const sotok = 10;
const a = 15;
const b = 25;
let s = sotok * 100;
console.log(s % (a * b));
console.log("Вторая задача");
let areaInCm = 15 * 100;
let oval = 600;
console.log(areaInCm - oval);
console.log("Третья задача");
let firstNumber = 10; //prompt("Введите первое число");
let secondNumber = 20; //prompt("Введите второе число");
let thirdNumber = 5; //prompt("Введите третье число");
console.log(Math.min(firstNumber, secondNumber, thirdNumber));
console.log("Четвертая задача");
let m = prompt("Введите первое число");
let n = prompt("Введите второе число");
const near = 10;
console.log(Math.abs(near - m) > Math.abs(near - n) ? n : m);

